version: 2.1
orbs:
  node: circleci/node@4.7.0
jobs:
  node-version:
    docker:
      - image: cimg/node:current
    steps:
      - checkout
      - node/install-packages
      - run: node --version
  build:
    docker:
      - image: cimg/node:current
    steps:
      - checkout
      - node/install-packages
      - run:
          command: npm run build
workflows:
  node-tests:
    jobs:
      - node-version
      - node/test
      - build
