version: 2.1
jobs:
  build:
    docker:
      - image: cimg/node:15.9.0
    steps:
      - checkout
      - node/install-packages
      - run:
          command: npm run build
orbs:
  node: cimg/node:15.9.0
workflows:
  node-tests:
    jobs:
      - node/test
      - build
